:remote config alias g Flights.g

schema.propertyKey("icao").Text().single().create()
schema.propertyKey("target").Text().single().create()
schema.propertyKey("dist").Int().single().create()
schema.propertyKey("city").Text().single().create()
schema.propertyKey("runways").Int().single().create()
schema.propertyKey("lat").Double().single().create()
schema.propertyKey("code").Text().single().create()
schema.propertyKey("id").Text().single().create()
schema.propertyKey("region").Text().single().create()
schema.propertyKey("desc").Text().single().create()
schema.propertyKey("type").Text().single().create()
schema.propertyKey("longest").Int().single().create()
schema.propertyKey("elev").Int().single().create()
schema.propertyKey("country").Text().single().create()
schema.propertyKey("source").Text().single().create()
schema.propertyKey("lon").Double().single().create()
schema.edgeLabel("route").single().properties("dist").create()
schema.edgeLabel("contains").single().create()
schema.vertexLabel("airport").properties("country", "code", "longest", "city", "elev", "icao", "lon", "type", "region", "runways", "lat", "desc", "id", "source", "target").create()
schema.vertexLabel("airport").index("byid").materialized().by("id").add()
schema.vertexLabel("airport").index("bysource").materialized().by("source").add()
schema.vertexLabel("airport").index("bytarget").materialized().by("target").add()
schema.vertexLabel("version").properties("code", "type", "desc", "id").create()
schema.vertexLabel("version").index("byid").materialized().by("id").add()
schema.vertexLabel("country").properties("code", "type", "desc", "id", "source").create()
schema.vertexLabel("country").index("byid").materialized().by("id").add()
schema.vertexLabel("country").index("bysource").materialized().by("source").add()
schema.vertexLabel("continent").properties("code", "type", "desc", "id", "source").create()
schema.vertexLabel("continent").index("byid").materialized().by("id").add()
schema.vertexLabel("continent").index("bysource").materialized().by("source").add()
schema.edgeLabel("route").connection("airport", "airport").add()
schema.edgeLabel("contains").connection("country", "airport").connection("continent", "airport").add()
